import { useEffect, useState, type ChangeEvent, type FormEvent } from 'react'
import { propertySchema, type PropertyFieldErrors } from '../../schemas/property.schema'
import type { PropertyFormValues } from '../../types/property'

interface Props { initialValues?: PropertyFormValues; existingImageUrl?: string | null; submitLabel: string; isSubmitting: boolean; serverError?: string; onSubmit: (values: PropertyFormValues) => Promise<void> }
const empty: PropertyFormValues = { title: '', description: '', availableDate: '', inspectionAt: '', isAvailable: true, latitude: '', longitude: '', price: '', numberOfRooms: '', image: null }

export default function PropertyForm({ initialValues = empty, existingImageUrl, submitLabel, isSubmitting, serverError, onSubmit }: Props) {
  const [values, setValues] = useState(initialValues)
  const [errors, setErrors] = useState<PropertyFieldErrors>({})
  const [preview, setPreview] = useState<string | null>(null)
  useEffect(() => setValues(initialValues), [initialValues])
  useEffect(() => { if (!values.image) { setPreview(null); return }; const url = URL.createObjectURL(values.image); setPreview(url); return () => URL.revokeObjectURL(url) }, [values.image])
  const set = (field: keyof PropertyFormValues, value: string | boolean | File | null) => { setValues((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: undefined })) }
  const imageChanged = (event: ChangeEvent<HTMLInputElement>) => set('image', event.target.files?.[0] || null)
  const submit = async (event: FormEvent) => { event.preventDefault(); const result = propertySchema.safeParse(values); if (!result.success) { const next: PropertyFieldErrors = {}; result.error.issues.forEach((issue) => { const field = issue.path[0] as keyof PropertyFieldErrors; if (!next[field]) next[field] = issue.message }); setErrors(next); return }; await onSubmit(values) }
  const inputClass = (field: keyof PropertyFormValues) => `form-input ${errors[field] ? 'border-red-400 focus:border-red-500 focus:ring-red-100' : ''}`
  return <form onSubmit={submit} noValidate className="space-y-8">
    {serverError && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{serverError}</div>}
    <section><h2 className="form-section-title">Property details</h2><p className="form-section-copy">Basic information guests will use to identify the property.</p><div className="mt-5 grid gap-5">
      <label className="form-label">Title<input className={inputClass('title')} value={values.title} onChange={(e) => set('title', e.target.value)} placeholder="e.g. Beach House" />{errors.title && <span className="form-error">{errors.title}</span>}</label>
      <label className="form-label">Description<textarea rows={5} className={inputClass('description')} value={values.description} onChange={(e) => set('description', e.target.value)} placeholder="Describe the property and its best features" />{errors.description && <span className="form-error">{errors.description}</span>}</label>
    </div></section>
    <section className="border-t border-slate-200 pt-8"><h2 className="form-section-title">Availability & pricing</h2><div className="mt-5 grid gap-5 sm:grid-cols-2">
      <label className="form-label">Available date<input type="date" className={inputClass('availableDate')} value={values.availableDate} onChange={(e) => set('availableDate', e.target.value)} />{errors.availableDate && <span className="form-error">{errors.availableDate}</span>}</label>
      <label className="form-label">Inspection date & time <span className="font-normal text-slate-400">(optional)</span><input type="datetime-local" className={inputClass('inspectionAt')} value={values.inspectionAt} onChange={(e) => set('inspectionAt', e.target.value)} />{errors.inspectionAt && <span className="form-error">{errors.inspectionAt}</span>}</label>
      <label className="form-label">Price (PHP)<input type="number" min="0" step="0.01" className={inputClass('price')} value={values.price} onChange={(e) => set('price', e.target.value)} placeholder="0.00" />{errors.price && <span className="form-error">{errors.price}</span>}</label>
      <label className="form-label">Number of rooms<input type="number" min="1" step="1" className={inputClass('numberOfRooms')} value={values.numberOfRooms} onChange={(e) => set('numberOfRooms', e.target.value)} placeholder="1" />{errors.numberOfRooms && <span className="form-error">{errors.numberOfRooms}</span>}</label>
    </div><label className="mt-5 flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 px-4 py-3"><input type="checkbox" checked={values.isAvailable} onChange={(e) => set('isAvailable', e.target.checked)} className="size-4 accent-teal-700" /><span><span className="block text-sm font-medium text-slate-700">Available for booking</span><span className="block text-xs text-slate-500">Turn this off to hide its availability status.</span></span></label></section>
    <section className="border-t border-slate-200 pt-8"><h2 className="form-section-title">Location</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="form-label">Latitude<input type="number" step="any" className={inputClass('latitude')} value={values.latitude} onChange={(e) => set('latitude', e.target.value)} placeholder="7.0731" />{errors.latitude && <span className="form-error">{errors.latitude}</span>}</label><label className="form-label">Longitude<input type="number" step="any" className={inputClass('longitude')} value={values.longitude} onChange={(e) => set('longitude', e.target.value)} placeholder="125.6128" />{errors.longitude && <span className="form-error">{errors.longitude}</span>}</label></div></section>
    <section className="border-t border-slate-200 pt-8"><h2 className="form-section-title">Property image</h2><p className="form-section-copy">JPEG, PNG, or WebP, up to 5 MB.</p><div className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-center">{(preview || existingImageUrl) && <img src={preview || existingImageUrl || ''} alt="Property preview" className="h-32 w-full rounded-xl border border-slate-200 object-cover sm:w-48" />}<label className="flex flex-1 cursor-pointer flex-col items-center rounded-xl border border-dashed border-slate-300 px-5 py-7 text-center hover:border-teal-500 hover:bg-teal-50/50"><span className="text-sm font-medium text-slate-700">{values.image ? values.image.name : existingImageUrl ? 'Choose a replacement image' : 'Choose an image'}</span><span className="mt-1 text-xs text-slate-500">Click to browse your files</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={imageChanged} className="sr-only" /></label></div>{errors.image && <span className="form-error mt-2">{errors.image}</span>}</section>
    <div className="flex justify-end border-t border-slate-200 pt-6"><button type="submit" className="btn-primary min-w-36" disabled={isSubmitting}>{isSubmitting ? 'Saving…' : submitLabel}</button></div>
  </form>
}
